[cursor.style]
blinking = "always"

[font]
size = 16

# Other Fonts
# "DankMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
dynamic_title = false
startup_mode = "Maximized"
opacity = 0.99             # fucks mission control in macos if its 1
