#max_width = 90
#comment_width = 70
#wrap_comments = true
#condense_wildcard_suffixes = true
#empty_item_single_line = false
#reorder_imports = true
#imports_granularity = "Crate"
#chain_width = 70
#fn_call_width = 70
#array_width = 80
#single_line_if_else_max_width = 60
# single_line_let_else_max_width = 60
