[mgr]
prepend_keymap = [
    { on = "<Enter>", run = "open", desc = "Open the selected files (or directories with Cursor)" },
    { on = "d", run = "remove --force", desc = "Remove files without confirmation" },
    { on = "<C-y>", run = [
        "plugin system-clipboard",
    ] },
    { on = "q", run = "quit --no-cwd-file", desc = "Quit without changing directory" },
    { on = "Q", run = "quit", desc = "Quit and change to current directory" },
]
