[mgr]
prepend_keymap = [
    { on = "d", run = "remove --force", desc = "Remove files without confirmation" },
    { on = "<C-y>", run = [
        "plugin system-clipboard",
    ] },
    { on = "q", run = "quit --no-cwd-file", desc = "Quit without changing directory" },
    { on = "<Enter>", run = "quit", desc = "Exit and cd to current directory" },
]
