[mgr]
prepend_keymap = [
    { on = "d", run = "remove --force", desc = "Remove files without confirmation" },
    { on = "<C-y>", run = [
        "plugin system-clipboard",
    ] },
    { on = "q", run = "quit --no-cwd-file", desc = "Quit without changing directory" },
    { on = "Q", run = "quit", desc = "Exit and cd to current directory" },
    { on = "<Enter>", run = "open", desc = "Open with the opener" },
    { on = "<C-u>", run = "seek -5", desc = "Scroll half page up in preview" },
    { on = "<C-d>", run = "seek 5", desc = "Scroll half page down in preview" }
]
