[mgr]
ratio = [2, 4, 4]
show_hidden = true
sort_by = "mtime"
sort_reverse = true
linemode = "mtime"

[opener]
directory = [
    { run = 'open "$@"', desc = "Open directory", for = "macos" },
]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Edit in Nvim", for = "macos" },
]
media = [
    { run = 'open -a "VLC" "$@"', orphan = true, desc = "Play in VLC", for = "macos" },
]
preview = [{ run = 'open "$@"', desc = "Open in preview", for = "macos" }]
image = [{ run = 'open "$@"', desc = "Open in default viewer", for = "macos" }]
archive = [{ run = 'open "$@"', desc = "Extract/Open archive", for = "macos" }]

[open]
rules = [
    { name = "*/", use = "directory" },
    # Video formats
    { name = "*.{mp4,mkv,avi,mov,wmv,flv,webm,mpeg,mpg,m4v,3gp}", use = "media" },
    # Audio formats  
    { name = "*.{mp3,aac,flac,wav,ogg,wma,alac,m4a,opus}", use = "media" },
    # Subtitle formats (also open with VLC for convenience)
    { name = "*.{srt,sub,ass,ssa,vtt}", use = "media" },
    # Image formats
    { name = "*.{jpg,jpeg,png,gif,bmp,tiff,webp,svg,ico,heic,avif}", use = "image" },
    # Archive formats
    { name = "*.{zip,tar,gz,bz2,xz,7z,rar}", use = "archive" },
    # PDF and documents
    { name = "*.pdf", use = "preview" },
    # Everything else opens in editor
    { name = "*", use = "edit" },
]
