vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<leader>w", "<cmd>w<CR>")
vim.keymap.set("n", "<leader>q", "<cmd>q<CR>")
vim.keymap.set("n", "-", "<cmd>Oil --float<CR>")
vim.keymap.set("n", "<leader>f", "<cmd>lua require('conform').format()<CR>")
vim.keymap.set("n", "<leader>cd", "<cmd>cd%:h<CR>")
