colourful: true

filekinds:
  normal: { foreground: "#C5C9C7" }
  directory: { foreground: "#8BA4B0" }
  symlink: { foreground: "#7AA89F" }
  pipe: { foreground: "#938AA9" }
  block_device: { foreground: "#E46876" }
  char_device: { foreground: "#E46876" }
  socket: { foreground: "#A4A7A4" }
  special: { foreground: "#957fb8" }
  executable: { foreground: "#7AA89F" }
  mount_point: { foreground: "#7fb4ca" }

perms:
  user_read: { foreground: "#C5C9C7" }
  user_write: { foreground: "#E6C384" }
  user_execute_file: { foreground: "#7AA89F" }
  user_execute_other: { foreground: "#7AA89F" }
  group_read: { foreground: "#A4A7A4" }
  group_write: { foreground: "#E6C384" }
  group_execute: { foreground: "#7AA89F" }
  other_read: { foreground: "#8EA4A2" }
  other_write: { foreground: "#E6C384" }
  other_execute: { foreground: "#7AA89F" }
  special_user_file: { foreground: "#957fb8" }
  special_other: { foreground: "#A4A7A4" }
  attribute: { foreground: "#8EA4A2" }

size:
  major: { foreground: "#8EA4A2" }
  minor: { foreground: "#87A987" }
  number_byte: { foreground: "#C5C9C7" }
  number_kilo: { foreground: "#A4A7A4" }
  number_mega: { foreground: "#8BA4B0" }
  number_giga: { foreground: "#957fb8" }
  number_huge: { foreground: "#957fb8" }
  unit_byte: { foreground: "#8EA4A2" }
  unit_kilo: { foreground: "#8BA4B0" }
  unit_mega: { foreground: "#957fb8" }
  unit_giga: { foreground: "#957fb8" }
  unit_huge: { foreground: "#7fb4ca" }

users:
  user_you: { foreground: "#C5C9C7" }
  user_root: { foreground: "#E46876" }
  user_other: { foreground: "#957fb8" }
  group_yours: { foreground: "#A4A7A4" }
  group_other: { foreground: "#938AA9" }
  group_root: { foreground: "#E46876" }

links:
  normal: { foreground: "#7AA89F" }
  multi_link_file: { foreground: "#7fb4ca" }

git:
  new: { foreground: "#87A987" }
  modified: { foreground: "#E6C384" }
  deleted: { foreground: "#E46876" }
  renamed: { foreground: "#7AA89F" }
  typechange: { foreground: "#957fb8" }
  ignored: { foreground: "#938AA9" }
  conflicted: { foreground: "#E46876" }

git_repo:
  branch_main: { foreground: "#C5C9C7" }
  branch_other: { foreground: "#957fb8" }
  git_clean: { foreground: "#87A987" }
  git_dirty: { foreground: "#E46876" }

security_context:
  colon: { foreground: "#938AA9" }
  user: { foreground: "#A4A7A4" }
  role: { foreground: "#957fb8" }
  typ: { foreground: "#A4A7A4" }
  range: { foreground: "#957fb8" }

file_type:
  image: { foreground: "#E6C384" }
  video: { foreground: "#938AA9" }
  music: { foreground: "#938AA9" }
  lossless: { foreground: "#7AA89F" }
  crypto: { foreground: "#A4A7A4" }
  document: { foreground: "#A292A3" }
  compressed: { foreground: "#E46876" }
  temp: { foreground: "#E46876" }
  compiled: { foreground: "#7fb4ca" }
  build: { foreground: "#A4A7A4" }
  source: { foreground: "#8BA4B0" }

punctuation: { foreground: "#938AA9" }
date: { foreground: "#E6C384" }
inode: { foreground: "#8EA4A2" }
blocks: { foreground: "#A4A7A4" }
header: { foreground: "#C5C9C7" }
octal: { foreground: "#7AA89F" }
flags: { foreground: "#957fb8" }

symlink_path: { foreground: "#7AA89F" }
control_char: { foreground: "#7fb4ca" }
broken_symlink: { foreground: "#E46876" }
broken_path_overlay: { foreground: "#A4A7A4" }
