# https://espanso.org/docs/
matches:
  - trigger: ":tx"
    replace: " think hard, answer in short. "

  - trigger: ":exa"
    replace: " use exa mcp server. "

  - trigger: ":c7"
    replace: " use context7 mcp server. "

  - trigger: ":rsd"
    replace: " use rust docs mcp server. "

  - trigger: ":ctx"
    replace: "do you want to handle this new request/petition? is your context window still manageable? if not, give me a prompt so that i can reset context and re-feed it to you. you can attach some file names and symbol names if you want."
