# https://espanso.org/docs/
matches:
  - trigger: ":exa"
    replace: "- use exa mcp server for web search and github search"

  - trigger: ":c7"
    replace: "- use context7 mcp server to search for the library/tool documentation"

  - trigger: ":rsd"
    replace: "- use rust-docs mcp server to search for the library/tool documentation (check if its embedded, if not, embed it first and then you can check its status and query for semantic search)"

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
