# https://espanso.org/docs/
matches:
  - trigger: ":exa"
    replace: "Note: you can use exa mcp server for semantic web search as well as github search if your `WebFetch` tool results need more refinement."

  - trigger: ":c7"
    replace: "Note: you can use context7 mcp server to search through documentation in libraries. it almost always has the popular libraries."

  - trigger: ":rsd"
    replace: "Note: you can use rust-docs mcp server to search for documentation about rust crates. it is powerful and uses vector embeddings. first check the embedded crates before you embed/query something"

  - trigger: ":ctx"
    replace: "do you want to handle this new request/petition? is your context window still manageable? if not, give me a prompt so that i can reset context and re-feed it to you. you can attach some file names and symbol names if you want."
