[manager]
prepend_keymap = [
    { on = "<Enter>", run = "open", desc = "Open the selected files (or directories with Cursor)" },
    { on = "d", run = "remove --force", desc = "Remove files without confirmation" },
    { on = "<C-y>", run = [
        "plugin system-clipboard",
    ] },
]
